### ISSUE TITLE
calls to correlation clustering fail 

### ISSUE THREAD

**Issue by nvanva** [FrancescoPeriti/CSSDetection#2]
Hello Francesco, thank you for an interesting paper and the published code! 

I'm trying to reproduce the results from the paper but have some problems. When running ```run_comparison.sh```, calls to ```model_evaluation.py``` fail because an argument ```weight_threshold``` is specified which does not exist for the function```cluster_correlation_search```: https://github.com/Garrafao/correlation_clustering/blob/c2b22186f2f858ee40dbff24b450a5ba49518a49/src/correlation.py#L17

I looked through different versions of https://github.com/Garrafao/correlation_clustering but couldn't find any version where this argument exists. Where can I take the version with this argument?
```
Traceback (most recent call last):                                                                                                                           
  File "/localscratch/12732071/CSSDetection/src/model_evaluation.py", line 320, in <module>
    clusters_metrics, clusters_labels, clusters_dists = WSI(dfs, gold_wsi_dfs)              
  File "/localscratch/12732071/CSSDetection/src/model_evaluation.py", line 221, in WSI
    classes, _ = cluster_correlation_search(graph,                          
TypeError: cluster_correlation_search() got an unexpected keyword argument 'weight_threshold' 
```

**Comment by FrancescoPeriti** [comment]
Hi, thanks for reaching out and sorry for the issue. We integrated a parameter `weight_threshold` during testing to experiment with different thresholds. This change just involved using a parameter (i.e., `weight_threshold`) instead of the fixed value 0.0 in line 231 of the original file: [https://github.com/Garrafao/correlation_clustering/blob/main/src/correlation.py](https://github.com/Garrafao/correlation_clustering/blob/main/src/correlation.py). In the end, we decided to use the default threshold and not experiment further (i.e., we set `weight_threshold`=0.0). However, we forgot to remove the parameter from the released code. We have now commented out the parameter in `model_evaluation.py`, and the code now works with the original `correlation_clustering.py` file
